// SPDX-License-Identifier: EPL-2.0

import { type IntlString, mergeIds, type Resource } from '@hcengineering/platform'
import gitlab, { gitlabId } from '@hcengineering/gitlab'
import { type Ref, type Space } from '@hcengineering/core'
import { type DocCreateFunction } from '@hcengineering/presentation'
import { type Handler, type IntegrationType } from '@hcengineering/setting'
import { type AnyComponent } from '@hcengineering/ui'

export default mergeIds(gitlabId, gitlab, {
  string: {
    SyncError: '' as IntlString,
    Retry: '' as IntlString,
    ReviewNotSent: '' as IntlString,
    Authorize: '' as IntlString,
    ReAuthorize: '' as IntlString,
    Authorized: '' as IntlString,
    NotAuthorized: '' as IntlString,
    NoRepositories: '' as IntlString,
    RefreshRepositories: '' as IntlString,
    ImageMode: '' as IntlString,
    ImageModeLink: '' as IntlString,
    ImageModeCopy: '' as IntlString,
    ImageModeLinkHint: '' as IntlString,
    ImageModeCopyHint: '' as IntlString,
    ImageNoAccess: '' as IntlString,
    ImageNotConnected: '' as IntlString,
    ImageUnavailable: '' as IntlString,
    GitlabImages: '' as IntlString,
    OpenInGitlab: '' as IntlString,
    LinkToProject: '' as IntlString,
    Unlink: '' as IntlString,
    LinkedTo: '' as IntlString,
    Unavailable: '' as IntlString,
    Processing: '' as IntlString,
    AutoClose: '' as IntlString,
    RequestFailed: '' as IntlString,
    CloseTab: '' as IntlString,
    KeepSettingsOpen: '' as IntlString,
    Repository: '' as IntlString,
    SetupTitle: '' as IntlString,
    SetupWhere: '' as IntlString,
    SetupUserOwned: '' as IntlString,
    SetupGroupOwned: '' as IntlString,
    SetupInstanceWide: '' as IntlString,
    SetupTrustedHint: '' as IntlString,
    SetupNameAndRedirect: '' as IntlString,
    SetupConfidentialScopes: '' as IntlString,
    SetupCopyCredentials: '' as IntlString,
    GitlabUrl: '' as IntlString,
    SelfManaged: '' as IntlString,
    ApplicationId: '' as IntlString,
    ApplicationSecret: '' as IntlString,
    KeepSecretHint: '' as IntlString,
    Save: '' as IntlString,
    Change: '' as IntlString,
    Remove: '' as IntlString,
    Copy: '' as IntlString,
    Copied: '' as IntlString,
    ConfiguredApp: '' as IntlString,
    OwnerMustConfigure: '' as IntlString,
    InvalidGitlabUrl: '' as IntlString,
    SetupEnterUrlFirst: '' as IntlString,
    DisconnectEveryone: '' as IntlString,
    DisconnectEveryoneConfirm: '' as IntlString,
    LinkFailed: '' as IntlString,
    UnlinkFailed: '' as IntlString,
    NotConfigured: '' as IntlString,
    AuthorizeLinkInvalid: '' as IntlString,
    IntegrationRepositories: '' as IntlString,
    SyncErrorMessage: '' as IntlString,
    UnlinkConfirm: '' as IntlString,
    RemoveAppConfirm: '' as IntlString,
    Draft: '' as IntlString,
    MergedAt: '' as IntlString,
    ClosedAt: '' as IntlString,
    Commits: '' as IntlString,
    Files: '' as IntlString,
    SourceBranch: '' as IntlString,
    TargetBranch: '' as IntlString,
    MergeStatus: '' as IntlString,
    MergeRequestState: '' as IntlString,
    Reviewers: '' as IntlString,
    StateOpened: '' as IntlString,
    StateMerged: '' as IntlString,
    StateClosed: '' as IntlString,
    StateLocked: '' as IntlString,
    ReadyToMerge: '' as IntlString,
    Conflict: '' as IntlString,
    Checking: '' as IntlString,
    PipelinePending: '' as IntlString,
    UnresolvedDiscussions: '' as IntlString,
    NeedsApproval: '' as IntlString,
    All: '' as IntlString,
    Active: '' as IntlString,
    Closed: '' as IntlString,
    ChangedFiles: '' as IntlString,
    WithoutRepository: '' as IntlString,
    CreateInGitlab: '' as IntlString,
    DiffUnavailable: '' as IntlString,
    DiffTooLarge: '' as IntlString,
    ApprovedBy: '' as IntlString,
    Approve: '' as IntlString,
    RevokeApproval: '' as IntlString,
    ConnectToApprove: '' as IntlString,
    Review: '' as IntlString,
    ReviewThread: '' as IntlString,
    ReviewComment: '' as IntlString,
    ReviewComments: '' as IntlString,
    ReviewApproved: '' as IntlString,
    ReviewUnapproved: '' as IntlString,
    ReviewRequestedChanges: '' as IntlString,
    ReviewReviewed: '' as IntlString,
    CommentedOnDiff: '' as IntlString,
    ResolveThread: '' as IntlString,
    UnresolveThread: '' as IntlString,
    ResolvedBy: '' as IntlString,
    Outdated: '' as IntlString
  },
  component: {
    Connect: '' as AnyComponent,
    Configure: '' as AnyComponent,
    GitlabIcon: '' as AnyComponent,
    IntegrationState: '' as AnyComponent,
    MergeRequests: '' as AnyComponent,
    MergeRequestPresenter: '' as AnyComponent,
    TitlePresenter: '' as AnyComponent,
    MergeRequestState: '' as AnyComponent,
    MergeRequestStateValuePresenter: '' as AnyComponent,
    MergeStatusValuePresenter: '' as AnyComponent,
    EditMergeRequest: '' as AnyComponent,
    GitlabIssueHeader: '' as AnyComponent,
    GitlabIssuePresenter: '' as AnyComponent,
    GitlabRepositoryPool: '' as AnyComponent,
    GitlabReviewPresenter: '' as AnyComponent,
    GitlabReviewThreadPresenter: '' as AnyComponent
  },
  handler: {
    DisconnectHandler: '' as Handler
  },
  function: {
    ShowForRepositoryOnly: '' as Resource<(spaces: Space[]) => Promise<boolean>>,
    UpdateIssue: '' as Resource<DocCreateFunction>
  },
  integrationType: {
    Gitlab: '' as Ref<IntegrationType>
  }
})
